Sa testing
maridoroshuk/cinema-lib pull request #8
Opened 2023-02-17 10:21 UTC by Shakhrai-Antony

2023-02-17 10:57 UTC, maridoroshuk commented
@Shakhrai-Antony  посмотри ошибки в деплое, исправь

2023-02-21 12:05 UTC, Shakhrai-Antony commented
почему-то не могу посмотреть ошибку. 404 ответ приходит

2023-02-21 12:51 UTC, maridoroshuk requested changes

2023-02-21 12:53 UTC, Shakhrai-Antony commented on src/components/Buttons/Button/interface.ts
> +  dataCy: string;
исправил

2023-02-21 13:12 UTC, maridoroshuk approved these changes

2023-02-21 13:16 UTC, merged